# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647795908aa712fa9cd2f76774efaf16a554fffdec5fe9d444f5d99b87cc643fd60f31fbd606d1cc53c9c81861e53d9f7f40e92da17cd7819bf996f4addce573

test:
  secret_key_base: de76b084d161bc99fa839305f5c64cff4b26883d613ec69301faac75699988f7d06f4a1d88a98373c305ceed55c6796353bce5e78102220e0883ff80daf28a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
