# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8b94bd1c01d8d9671879eecf4037a19622caa034af3cc9d71fc11cd8df0c9923e983b8fb215bcbe57df2e5b5d0cc6c030a3c3dfd39d8ce69e79a04491d2d973

test:
  secret_key_base: 5807d934ef234b1c0a481d5e0705f37483effe1177bc6faefeaed5630f8c2e2243ebfa64b9990e304decdf850e2ae83b9ae7138ea48d1fd1a882dd6b7a74157e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
